/**
 * Keystone Hardware Wallet - Example Data and Constants
 * Contains default values, example transactions, and sample URs for testing
 */

// UR type constants
export const UR_TYPES = {
    IOTA_SIGNATURE: 'iota-signature',
    IOTA_SIGN_REQUEST: 'iota-sign-request',
    UR_PREFIX: 'ur:',
} as const;

// Address prefixes
export const ADDRESS_PREFIXES = {
    HEX: '0x',
    IOTA1Q: 'iota1q',
} as const;

// UI labels and messages
export const UI_LABELS = {
    IOTA_SIGNATURE_TYPE: 'IOTA Signature',
    ADDRESS_PLACEHOLDER: 'IOTA account address (hex)',
    DERIVATION_PATH_PLACEHOLDER: "m/44'/4218'/0'/0'/0'",
} as const;

// Default connection data (used as fallback when no Keystone device is connected)
export const DEFAULT_DERIVATION_PATHS = "m/44'/4218'/0'/0'/0'";
export const DEFAULT_MASTER_FINGERPRINT = '70ee3cac';
export const DEFAULT_ACCOUNT_ADDRESS =
    '0xb9cbe931d4569659e5235346a9361642be3c045112bdc2676dd1e74d14d7c0a2';
export const DEFAULT_WALLET_ORIGIN = 'IOTA Wallet';

// Default sign request data
export const DEFAULT_REQUEST_ID = '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d';

// Example transaction bytes (Base64 encoded)
export const EXAMPLE_RAW_TRANSACTION_BYTES_1 =
    'AAACAAgAypo7AAAAAAAgVTsVB+RtZMfs4jACWZp8XfogU5tbYbqiYDYTtMQdQcQCAgABAQAAAQEDAAAAAAEBAFU7FQfkbWTH7OIwAlmafF36IFObW2G6omA2E7TEHUHEAXzaorDJSfN6qSVVUDHjdog/B1KoxmcB+gSwrJ/B44ahuzcAAAAAAAAgTuYTwz7DtRoLbEVHWVZ/ehscmfPcHKW1aFzwWFydTKVVOxUH5G1kx+ziMAJZmnxd+iBTm1thuqJgNhO0xB1BxOgDAAAAAAAA4G88AAAAAAAA';

export const EXAMPLE_RAW_TRANSACTION_BYTES_2 =
    'AAAFAQGpKmeuioxkSs+m3VpNgJiiCwe2Bhy/Nq/42u87qJKRP0VMyxUAAAAAAQAODW5uYWFtbWVlLmlvdGEACICWmAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgEAAAAAAAAAAAAgVTsVB+RtZMfs4jACWZp8XfogU5tbYbqiYDYTtMQdQcQFAOEoSHABhISnoSJVrrtze2uYtH1lK4QuovMkSZ/xY6ZIB3BheW1lbnQRaW5pdF9yZWdpc3RyYXRpb24AAgEAAAEBAAIAAQECAAAe+si/IArMpktiznVVfNcjIxD8jE6pCWBIfSkIBV/JTwhwYXltZW50cxNoYW5kbGVfYmFzZV9wYXltZW50AQcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgRpb3RhBElPVEEAAwEAAAIAAAIBAADhKEhwAYSEp6EiVa67c3trmLR9ZSuELqLzJEmf8WOmSAdwYXltZW50CHJlZ2lzdGVyAAMCAgABAAABAwABAQIDAAEEAFU7FQfkbWTH7OIwAlmafF36IFObW2G6omA2E7TEHUHEAXzaorDJSfN6qSVVUDHjdog/B1KoxmcB+gSwrJ/B44ahuzcAAAAAAAAgTuYTwz7DtRoLbEVHWVZ/ehscmfPcHKW1aFzwWFydTKVVOxUH5G1kx+ziMAJZmnxd+iBTm1thuqJgNhO0xB1BxOgDAAAAAAAAYHZvAAAAAAAA';

// Example signature data (Hex format)
export const EXAMPLE_SIGNATURE_HEX =
    'f4b79835417490958c72492723409289b444f3af18274ba484a9eeaca9e760520e453776e5975df058b537476932a45239685f694fc6362fe5af6ba714da6505';
export const EXAMPLE_PUBLIC_KEY_HEX =
    'bfa73107effa14b21ff1b9ae2e6b2e770232b7c29018abbf76475b25395369c0';

// Example IOTA Sign Request UR (single part)
export const EXAMPLE_DECODE_SIGN_REQUEST_UR =
    'UR:IOTA-SIGN-REQUEST/OXADTPDAGDWLTPPLWPDEHEFDGULGKOPSJTKEOXLSHPAOHDUOAEAEAEAEAEAOAEAYAESGNYFRAEAEAEAEAECXIDHNWKLNAMUYWLGOGLGWGSAOKOTYGADTNTCWCEDRNDGHHDIDWLTNURWKFRJOFMEOAOAOAEADADAEAEADADAOAEAEADADAEGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSADKETNOEPFSOGAWFKNPTDAGOGDEHVLKOLOFHATGMPDSWIOADZSAAPFPSNESEVLLNOYRKEMAEAEAEAEAEAECXGLVABWSRFMSRRECYBDJZFEFLHKHFLBKNCWCENLWFUOCEONREISHHWTHDHHNTGSONGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSVSAXAEAEAEAEAEAEVTJLFNAEAEAEAEAEAEAXLYTAADDYOEADLECSDWYKCFBEKNYKAOYKAEYKAEYKAOCYJOWYFNPSAALYHDCXGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSWDFZPTVO';

// Example IOTA Signature UR
export const EXAMPLE_SIGNATURE_UR =
    'UR:IOTA-SIGNATURE/OTADTPDAGDNDCAWMGTFRKIGRPMNDUTDNBTKGFSSBJNAOHDFZTDOLDWQZUYGLUYHGCKGOFNIHMTVAONCHENTYKBJOAOHFCAKEJKBNKNLRYTTBTADNDIIYQDWLZEYTAXTBIAOYPSDNBETDLDLKGTMKLAWFFGNTCTJEJPSGIHHKNYLNLUAXAXHDCXBEKOSTZCRSWMTLSFASFXNLROHGNYCPYKVLNSVYGRROTAEOWPGDSSWEBALFTKGYCXYNMEOXBT';

// Example multipart IOTA Sign Request UR (for testing multipart functionality)
export const EXAMPLE_MULTIPART_SIGN_REQUEST_UR = `UR:IOTA-SIGN-REQUEST/1-2/LPADAOCFAONSCYKBBBMWSSHKADGLONADTPDAGDNDCAWMGTFRKIGRPMNDUTDNBTKGFSSBJNAOHKAOEMAEAEAEAEAEAHADADPTDRIOPLLELKIEGETKOLUTHTGTLAMKOEBDATRPAMCERSENPEYATNWSFRPDMOMEFHFEGSSBBZAEAEAEAEADAEBABTJTJTHSHSJNJNIHIHDMINJLJYHSAEAYLAMTMKAEAEAEAEAEADADAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAMADAEAEAEAEAEAEAEAEAECXGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSAHAEVYDEFDJOADLRLROSOYCPGOPLRKJKKGJEMKQZKIIHDNLRDMOEWFDKGANEWNIAOLFDATJOHSKKJNIHJTJYBYINJTINJYHEJPIHIOINJKJYJPHSJYINJLJTAEAOADAEAEADADAEAOAEADADAOAEAECKZSSPRSCXBKSFOLGRIDTOKPGOKETSCNCNBEZTLKGLPTASHNFDKIDTAYAHHESOGWAYJOHSKKJNIHJTJYJKBWISHSJTIEJZIHHEIDHSJKIHHEJOHSKKJNIHJTJYADATAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAETONSWTRT
UR:IOTA-SIGN-REQUEST/2-2/LPAOAOCFAONSCYKBBBMWSSHKADGLAEAEAEAEAEAEAEAEAEAEAEAEAOAAINJLJYHSAAGAGWGHFPAEAXADAEAEAOAEAEAOADAEAEVYDEFDJOADLRLROSOYCPGOPLRKJKKGJEMKQZKIIHDNLRDMOEWFDKGANEWNIAOLFDATJOHSKKJNIHJTJYAYJPIHIOINJKJYIHJPAEAXAOAOAEADAEAEADAXAEADADAOAXAEADAAAEGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSADKETNOEPFSOGAWFKNPTDAGOGDEHVLKOLOFHATGMPDSWIOADZSAAPFPSNESEVLLNOYRKEMAEAEAEAEAEAECXGLVABWSRFMSRRECYBDJZFEFLHKHFLBKNCWCENLWFUOCEONREISHHWTHDHHNTGSONGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSVSAXAEAEAEAEAEAEHNKOJLAEAEAEAEAEAEAXLYTAADDYOEADLECSDWYKCFBEKNYKAEYKAEYKAEYKAOCYJOWYFNPSAALYHDCXRHSBWLEHTYHFMTHKVWCNGUFGPTENCMFWRNFNAAGYBGRYSAIOJNTTVDGTBBTSRTOEAHJEGAGWGHFPCXHGHSJZJZIHJYWZESHLIH
UR:IOTA-SIGN-REQUEST/3-2/LPAXAOCFAONSCYKBBBMWSSHKADGLONADTPDAGDNDCAWMGTFRKIGRPMNDUTDNBTKGFSSBJNAOHKAOEMAEAEAEAEAEAHADADPTDRIOPLLELKIEGETKOLUTHTGTLAMKOEBDATRPAMCERSENPEYATNWSFRPDMOMEFHFEGSSBBZAEAEAEAEADAEBABTJTJTHSHSJNJNIHIHDMINJLJYHSAEAYLAMTMKAEAEAEAEAEADADAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAMADAEAEAEAEAEAEAEAEAECXGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSAHAEVYDEFDJOADLRLROSOYCPGOPLRKJKKGJEMKQZKIIHDNLRDMOEWFDKGANEWNIAOLFDATJOHSKKJNIHJTJYBYINJTINJYHEJPIHIOINJKJYJPHSJYINJLJTAEAOADAEAEADADAEAOAEADADAOAEAECKZSSPRSCXBKSFOLGRIDTOKPGOKETSCNCNBEZTLKGLPTASHNFDKIDTAYAHHESOGWAYJOHSKKJNIHJTJYJKBWISHSJTIEJZIHHEIDHSJKIHHEJOHSKKJNIHJTJYADATAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAEAETLCKFDIO
UR:IOTA-SIGN-REQUEST/4-2/LPAAAOCFAONSCYKBBBMWSSHKADGLAEAEAEAEAEAEAEAEAEAEAEAEAOAAINJLJYHSAAGAGWGHFPAEAXADAEAEAOAEAEAOADAEAEVYDEFDJOADLRLROSOYCPGOPLRKJKKGJEMKQZKIIHDNLRDMOEWFDKGANEWNIAOLFDATJOHSKKJNIHJTJYAYJPIHIOINJKJYIHJPAEAXAOAOAEADAEAEADAXAEADADAOAXAEADAAAEGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSADKETNOEPFSOGAWFKNPTDAGOGDEHVLKOLOFHATGMPDSWIOADZSAAPFPSNESEVLLNOYRKEMAEAEAEAEAEAECXGLVABWSRFMSRRECYBDJZFEFLHKHFLBKNCWCENLWFUOCEONREISHHWTHDHHNTGSONGOFRBZATVEJNIESTWPVODYAOHKNYKEHLZSCXGUNDHPHSRDOEHNENBWQZSSCAFPSSVSAXAEAEAEAEAEAEHNKOJLAEAEAEAEAEAEAXLYTAADDYOEADLECSDWYKCFBEKNYKAEYKAEYKAEYKAOCYJOWYFNPSAALYHDCXRHSBWLEHTYHFMTHKVWCNGUFGPTENCMFWRNFNAAGYBGRYSAIOJNTTVDGTBBTSRTOEAHJEGAGWGHFPCXHGHSJZJZIHJYUERNMWLK`;

// QR Animation constants
export const MAX_FRAGMENT_LENGTH = 400;
export const DEFAULT_INTERVAL = 250;

/**
 * Initialize form fields with example data
 * This function sets default values for transaction-related fields only.
 * Account-related values should only be populated after scanning Keystone account data.
 */
export function getExampleData() {
    return {
        requestId: DEFAULT_REQUEST_ID,
        walletOrigin: DEFAULT_WALLET_ORIGIN,
        signatureHex: EXAMPLE_SIGNATURE_HEX,
        publicKeyHex: EXAMPLE_PUBLIC_KEY_HEX,
        rawTransactionBytes: EXAMPLE_RAW_TRANSACTION_BYTES_1,
        rawTransactionBytes2: EXAMPLE_RAW_TRANSACTION_BYTES_2,
        decodeSignRequestUR: EXAMPLE_DECODE_SIGN_REQUEST_UR,
        exampleSignatureUR: EXAMPLE_SIGNATURE_UR,
        exampleMultiSignRequestUR: EXAMPLE_MULTIPART_SIGN_REQUEST_UR,
        // Connection data - initially set to defaults but should be overridden by scanning
        derivationPaths: DEFAULT_DERIVATION_PATHS,
        masterFingerprint: DEFAULT_MASTER_FINGERPRINT,
        accountAddress: DEFAULT_ACCOUNT_ADDRESS,
    };
}

/**
 * Get example transaction descriptions for UI display
 */
export const TRANSACTION_EXAMPLES = {
    simple: {
        title: '📄 Load Example TX 1 (Simple Transfer)',
        description: 'Simple IOTA transaction - coin transfer',
        data: EXAMPLE_RAW_TRANSACTION_BYTES_1,
    },
    complex: {
        title: '📄 Load Example TX 2 (Complex)',
        description: 'Complex IOTA transaction - domain registration with payments',
        data: EXAMPLE_RAW_TRANSACTION_BYTES_2,
    },
} as const;
